services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.prod
    container_name: astro-app
    ports:
      - "4321:4321"
    environment:
      NODE_ENV: production
    depends_on:
      - redis
    env_file:
      - .env
      
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
